### PR TITLE
feat: Add TVL to Node Operator "more info"

### PR DESCRIPTION
**Pull request by KevinChristopher1014**
https://trello.com/c/OfhcNvJy/421-add-tvl-to-node-operator-more-info

### CODE REVIEW

**Review by leckylao — APPROVED** [review]

**Review by aaron-alderman — CHANGES_REQUESTED** [review]
Need to wait for all PR before merging

**Comment by aaron-alderman** [comment]
Please attach dependant PRs in other repositories to this PR

**Comment by KevinChristopher1014** [comment]
https://github.com/SwellNetwork/backend/pull/182

**Comment by KevinChristopher1014** [comment]
no needed

**Pull request closed without merging**
